"""empty message

Revision ID: af49fb321c27
Revises: 
Create Date: 2019-09-03 15:58:21.363819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af49fb321c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('pub_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'pub_date')
    # ### end Alembic commands ###
